version: "3"

services:
  # Database
  db:
    image: mysql:5.7
    container_name: bot_db
    user: "1000:1000"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ONETIME_PASSWORD
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_ROOT_HOST

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin:5.2.0-apache
    container_name: bot_db_admin
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_HOST
      - MYSQL_ROOT_PASSWORD

  # python
  telebot:
    depends_on:
      - db
    image: telebot:latest
    container_name: bot
    build:
      context: app
      dockerfile: ../Dockerfile
    ports:
      - "8081:8081"
    environment:
      - DB_HOST

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "${HOME}/mysql"
