version: "3"

services:
  # Database
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ONETIME_PASSWORD
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_ROOT_HOST

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin:5.2.0-fpm-alpine
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_HOST
      - MYSQL_ROOT_PASSWORD

  telebot:
    depends_on:
      - db
    image: telebot:latest
    build:
      context: app
      dockerfile: ../Dockerfile

volumes:
  - db_data:${HOME}/mysql:rw